### ISSUE TITLE
No scene to inspect. Please export it as window.scene.

### ISSUE THREAD

**Issue by kiko-rodriguez** [jeromeetienne/threejs-inspector#11]
It runs but it's not detecting my scene. The error on the console is:

three.js inspector: no scene to inspect. Please export it as window.scene.

What is a window.scene? Can you help me in understanding what the inspector is expecting to load my scene and objects?

**Comment by jeromeetienne** [comment]
`window.scene` is a global variable which contains the THREE.Scene you wish to inspect.

So in your code you add something similar to

```
window.scene = myScene;
```

**Comment by Zob1** [comment]
I also ran into this issue but this fixed it. It could be common if a lot of people use multiple scenes or different variable names for their scenes. Great tool! Very helpful!
