### ISSUE TITLE
Injected script breaks console.log for everything else on page.

### ISSUE THREAD

**Issue by martikaljuve** [jeromeetienne/threejs-inspector#17]
Since the scripts are injected into the current page, `console.log` is disabled for every other script running on the page as well, which is not very desirable.

https://github.com/jeromeetienne/threejs-inspector/blob/38a2505fc1e166d9853b41c6b417687786332c48/src/panel/inspected-win/00-inspected-win-prefix.js#L52

**Comment by snovak** [comment]
This was killing me!. Please fix.  Took the better part of an afternoon to realize what had happened.

**Comment by jeromeetienne** [comment]
Sorry about the delay, I fixed it in the .12 version

**Comment by jeromeetienne** [comment]
https://github.com/jeromeetienne/threejs-inspector/blob/cb2cf92accb3fb921e260e50c2c662c10312b8ae/src/panel/inspected-win/00-inspected-win-prefix.js#L51 here is the change
