### ISSUE TITLE
Unable to work when the three.js is imported by ES6 Module.

### ISSUE THREAD

**Issue by gogoend** [jeromeetienne/threejs-inspector#40]
In the rencent version of three.js (107dev), the three.js in official examples is imported by ES6 Module, instead of using “src” attribute on script tag. When I try to inspect the scene, it always tolds me "in 00-injected_script-init.js: three.js is NOT present." ,and I cannot see anything in threejs-inspector.

**Comment by zwickmueller** [comment]
make sure to export the scene as well as THREE when working with the ES6 Module [as stated here](https://github.com/jeromeetienne/threejs-inspector#how-to-be-sure-the-extension-find-your-scene), so  
`window.scene = scene;` and `window.THREE = THREE;` and dont forget to refresh. That solved it for me (three v107)

**Comment by gogoend** [comment]
Got it ,thanks
