### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by manurueda** [jeromeetienne/threejs-inspector#8]
1. Added the plugin via chrome store
2. Opened a few local / online threeJS demos and it did not worked
3. Reopened Chrome (just in case), it does not worked

*Always pressed reload

![image](https://cloud.githubusercontent.com/assets/3317934/10269066/31493eca-6acb-11e5-9554-72062fa7ff5d.png)

**Comment by manurueda** [comment]
I tried the other plugin, threeJS editor extension and it works fine with local files. I am gonna try to install it from source and let you know. Thank you, JM

**Comment by manurueda** [comment]
1. Installed from /src instead of Chrome extension and now it works pretty well with local files. 
2. With this online example it does not flush any content to the object tree  but now it shows all buttons. ref. http://threejs.org/examples/#webgl_geometry_cube
   > It seems it does not recognize where the threeJS code is, console log says 'three.js is not present'

**Comment by kenmoore** [comment]
I couldn't get it to work either.  I tried on a simple local file as well as http://www.insidious-movie.net/entertheroom/# ... in both cases all I ever see is the "the extension needs to reload the page [Reload]" screen in the Three.js Inspector tab

**Comment by dage** [comment]
I have the same issue. I only get the reload button even when going to the official three.js examples at http://threejs.org/examples/.  
I'm using Chrome v47.0.2526.80 on Windows 7.

**Comment by Coder2012** [comment]
Also get the reload button on any threejs example

Chrome v47.0.2526.106 on Window 7.

**Comment by KillerJim-DVG** [comment]
I found something similar, but if you press reload a few times (quickly) on the page I was viewing I did get it to work..

However, I'm seeing constant "PerspectiveCamera" being shown; so you really need to pause the JS to use the inspector..

Very nice work, can see real potential for new users trying to understand why things aren't right

**Comment by supermoos** [comment]
The new update doesn't work at all (using r73), the previous one worked maybe 20% of the time :) It's a really nice tool. Just so weird with these miss / hit initializations.

**Comment by jeromeetienne** [comment]
hello all, i just refactored the whole devtool <-> extension part. it was a mess. it is now more under controls. 

To code a devtools extension isn't too simple :)  https://developer.chrome.com/extensions/devtools 

i want to make this one work in all case. but i dont have all the answer. i look forward collborating with all of you guys

**Comment by supermoos** [comment]
For me the problem was that I wasn't exposing my THREE.Scene object as a global variable. Putting it on the window like so:

```
var myScene = new THREE.Scene();
window.scene = myScene;
```

solved it for me.

I think this should be added as a helper text on the initial splash screen, instead of just writing "Splash" ;-)  
It's a rather big requirement for the extension to require you to name your scene variable "scene" and having it globally available.

**Comment by jeromeetienne** [comment]
@supermoos thanks! i added the communication.

I am all open about detection mechanism, how would you suggest to detect the scene ?

**Comment by hellmark1990** [comment]
Exposing of **THREE** object solved this issue for me:
```
import` * as THREE from './node_modules/three/build/three.module.js';       
window.THREE = THREE;
```

**Comment by mshamaseen** [comment]
still not working for me in chrome, but three js extension is working on FF.
maybe because am using an Iframe for my threejs scene?
even though I added:

`var myScene = new THREE.Scene();
window.scene = myScene;
window.parent.scene = myScene;`
